language: node_js
node_js:
- iojs
- '7'
deploy:
  provider: s3
  access_key_id: AKIAJIWP7XHYWI2NSVSA
  secret_access_key:
    secure: tph2IOza3A3gQ9KrzjjjeSbfmt4q6Sz9CPdTcQL/rJ7dB+dkQVyw4jHX12k5Z0gEcbICl3yoouVPmKUWa56Kv/cyccfYVH9diL0qVcrScBgHPlYot+/0h8oREPVKyearBbspbsi4/V169GsyfPtN96NLergxBlrEv3Vfm9ra32meCageD9+i3uC87tyIHLkJxSm1TDAMRKj/BLRaW7tKGY++m8+Cgxv1/FF2CdsCZMjDiPW5QkN9R9pxvj06Ec4vv3dy6ejoInECIFkV68DUlSg5TWBgoRSku/GnBUjbnWKnNt8KQsu8KXHRRZ+t+Lf4Q4bbrLB24eAl+WcOKM+ci26dflaM1EFC887Fa9QBl2HR7X0sfv7qs+mfzhAIr9XSTepFuciGzrQAYZASy1dwxPyxTNEw9xCvoiEZ2nmuVZCGzM3BTT9rLvyAZ4oTeBUZuEC7HyuXyCzrLQwHgyxhlALAvfAMWt9QAYdGu1qO6cVUaYDTTFJLqlc84YyRlNISsDD3OrXDsuVP/kMgKOoo7Fk/IxJZeGbKP6rbVCG3ZpZpKXLm70h+GnHI7FSv9VZhoPI7HqsnwKSdSuaFchPEfyx04htX58YlXKgOljrop5wnFyzMlO/gzkTEGy9qIYksKoUfg5ePvVzVHAReXuLGmgW7k7Kt9n4Uu6C63Yc1gdI=
  bucket: jleiken.com
  acl: ''
  on:
    repo: jleiken/Portfolio-Website
